version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: propital-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: propital
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: pg_isready -U postgres -d propital
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: propital-api
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=propital
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: npm run start:dev

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 